#!/usr/bin/python2
from IPython import embed

from mcmatch.db.pg_database import PgFunDB
from mcmatch import cluster
from mcmatch.metric.counter import counter_metrics
from mcmatch.metric.aggregator import MetricAggregator
all_metrics = MetricAggregator([counter_metrics[c]() for c in counter_metrics])

fdb = PgFunDB()

embed()
